/**
 * Class Name  : SFSConstants
 * Description : This class has constants related GoEd implementation
 * Author      : Financial Spectra
 * 
 */
public class SFSConstants{

    public static final String OPP_APPLICATION_MAPPING         = 'Opportunity_Application_Mapping';

    public static final String AMOUNT_DISBURSED_ITEMIZATION    = 'AMOUNT_DISBURSED';
    public static final String DNL_STATUS_FINAL_SETTLEMENT_REACHED = 'Final Settlement Reached';
    public static final String VCL_STATUS_LEAD_UW_APPROVED = 'Lead Underwriter Approved';


}