/*
 * Class   : WS_Constants
 * Purpose : Constants used in Web Service classes
 * Author  : Financial Spectra
 */
public class WS_Constants {
    
    public static final String CREDIT_PULL_NAMED_CRED = 'creditPuller';
    public static final String NUDEBT_ORG_NAMED_CRED = 'NuDebtOrg';

    public static final String GET   = 'GET';
    public static final String PUT   = 'PUT';
    public static final String POST  = 'POST';
    public static final String PATCH = 'PATCH';

}